name: auto-republish-evans

# on:
#   schedule:
#     - cron: 0/30 * * * *
on: push

env:
  # CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
  GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  # FLP_API_TOKEN_STAGING: ${{ secrets.FLP_API_TOKEN_STAGING }}
  FLP_API_TOKEN_PROD: ${{ secrets.FLP_API_AUTO_REPUBLISH_EVANS_TOKEN }}
  GATSBY_ALGOLIA_SEARCH_ONLY_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_ONLY_KEY }}
  # GATSBY_TEST_STRIPE_PUBLISHABLE_KEY: ${{ secrets.GATSBY_TEST_STRIPE_PUBLISHABLE_KEY }}
  GATSBY_PROD_STRIPE_PUBLISHABLE_KEY: ${{ secrets.GATSBY_PROD_STRIPE_PUBLISHABLE_KEY }}
  GATSBY_FLP_API_ENDPOINT_PROD: ${{ secrets.GATSBY_FLP_API_ENDPOINT_PROD }}
  # GATSBY_FLP_API_ENDPOINT_STAGING: ${{ secrets.GATSBY_FLP_API_ENDPOINT_STAGING }}
  DOCS_REPOS_ROOT: ${{ github.workspace }}/evans
  DEPLOYING: true
  GATSBY_NETLIFY_CONTEXT: 'production'
  SLACK_API_TOKEN_WORKSPACE_MAIN: ${{ secrets.SLACK_API_TOKEN_WORKSPACE_MAIN }}
  SLACK_API_TOKEN_WORKSPACE_BOT: ${{ secrets.SLACK_API_TOKEN_WORKSPACE_BOT }}
  CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
  CLOUD_STORAGE_BUCKET: ${{ secrets.CLOUD_STORAGE_BUCKET }}
  CLOUD_STORAGE_ENDPOINT: ${{ secrets.CLOUD_STORAGE_ENDPOINT }}
  CLOUD_STORAGE_KEY: ${{ secrets.CLOUD_STORAGE_KEY }}
  CLOUD_STORAGE_SECRET: ${{ secrets.CLOUD_STORAGE_SECRET }}

jobs:
  check_should_republish:
    name: check-should-republish
    runs-on: ubuntu-latest
    outputs:
      should_republish: ${{ steps.check.outputs.should_republish }}
      build_data_cloud_filepath: ${{ steps.check.outputs.build_data_cloud_filepath }}
    steps:
      - name: check
        id: check
        uses: friends-library-dev/action-ts-pack/actions/should-republish-evans@04d36a3ae391dca534e8b7a43b178ccccf7e1d7b
        with:
          flp_api_token: ${{ secrets.FLP_API_AUTO_REPUBLISH_EVANS_TOKEN }}
          flp_api_endpoint: ${{ secrets.FLP_API_ENDPOINT_PROD }}

  republish_en:
    name: republish-en
    needs: check_should_republish
    runs-on: ubuntu-latest
    if: needs.check_should_republish.outputs.should_republish == 'true'
    steps:
      - name: echo
        run: echo DEPLOY EN HERE
      - name: echo2
        run: echo OUTPUT ${{ needs.check_should_republish.outputs.should_republish }}

  skip_republish:
    name: skip-republish
    needs: check_should_republish
    runs-on: ubuntu-latest
    if: needs.check_should_republish.outputs.should_republish != 'true'
    steps:
      - name: echo
        run: echo DO NOT DEPLOY HERE
      - name: echo2
        run: echo OUTPUT ${{ needs.check_should_republish.outputs.should_republish }}

  # republish_en:
  #   name: republish-en
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - uses: actions/checkout@v2
  #       with:
  #         repository: friends-library-dev/evans
  #         path: evans
  #     - uses: bahmutov/npm-install@v1
  #       with:
  #         working-directory: evans
  #     - name: clone-friend-repos
  #       run: cd evans && npx friend-repos-clone-all .
  #     - name: build:en
  #       run: cd evans && npm run build:en
  #     - name: deploy
  #       id: deploy
  #       uses: friends-library-dev/action-ts-pack/actions/deploy@651ed81c0b83529cac93ffeeaa43a39ec49c5104
  #       with:
  #         netlify_api_token: ${{ secrets.NETLIFY_API_TOKEN }}
  #         site_id: ${{ secrets.DEPLOY_SITE_ID_EN }}
  #         build_dir: evans/public
  #         github_token: ${{ github.token }}
